project:
  type: website
  pre-render: _pre-render.r

website:
  title: ""
  description: "Community College Planning and Research Organization"
  favicon: "images/ccpro-transparent-background.png"
  navbar:
    background: primary
    logo: "images/ccpro-white-nc-transparent-background.png"
    logo-href: "/"
    left:
      - href: index.qmd
        text: Home
      - href: pages/regions.qmd
        text: Regions
      - href: pages/resources.qmd
        text: Resources
      - href: pages/documents.qmd
        text: Documents
      - href: pages/conferences.qmd
        text: Conferences/Meetings
      - href: pages/membership-directory.qmd
        text: Membership Directory
      # - href: pages/job-postings.qmd
      #   text: Job Postings <!-- Uncomment when job postings page is needed -->
      - href: pages/membership-form.qmd
        text: Membership Form
      - href: pages/executive-committee.qmd
        text: Executive Committee


  page-footer:
    center: "CCPRO – Community College Planning and Research Organization"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
