---
title: "Membership Directory"
toc: true
echo: false
warning: false
---
Utilize the table below to find contact information for CCPRO members. The directory is updated quarterly, so please check back for the most current information.

To sign up for the directory, please contact the [CCPRO Webmaster](officers.qmd) to be added to the list. The directory is intended for use by CCPRO members only.

```{r}
#| label: libraries and data
library(dplyr) # Load dplyr for data manipulation
library(stringr) # Load stringr for string manipulation
library(DT) # Load DT for interactive tables
library(readxl) # Load readxl for reading Excel files

directory <- read_excel(
  "../documents/CCPRO_Directory_10312025.xlsx",
  sheet = "CCPRO_Directory"
) |> # Read in the directory from Excel: CCPRO_Directory_10312025.xlsx Sheet: CCPRO_Directory
  mutate(
    college_website = str_remove(college_website, ",$")
  ) # Clean up any trailing commas in the college_website column
```

```{r}
#| label: directory table
directory |>
  datatable(
    # Create an interactive datatable using DT (HTML widget)
    options = list(pageLength = 10, autoWidth = TRUE), # Set table length and auto width
    rownames = FALSE, # Remove row names
    colnames = c(
      "Member Name",
      "Title",
      "Region",
      "College",
      "College Address",
      "College Website",
      "Phone",
      "Email",
      "SACSCOC Liaison",
      "Excecutive Committee Member"
    ) # Clean column names for display
  )
```
